version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - persist_to_workspace:
          root: .
          paths:
            - build_output

  show-readme:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Display ReadMe
          command: cat build_output/README.md

workflows:
  say-hello-workflow:
    jobs:
      - build
      - show-readme:
          requires:
            - build